### ISSUE TITLE
One color for each ruler

### ISSUE THREAD

**Issue by piranna** [lexicalunit/multi-wrap-guide#3]
Allow to define a different color for each ones of the rules

**Comment by lexicalunit** [comment]
So I figured out how to do this simply using your `style.less` file:

``` less
atom-text-editor::shadow {
  .multi-wrap-guide:nth-child(1) .multi-wrap-guide-line {
    background-color: white;
  }

  .multi-wrap-guide:nth-child(2) .multi-wrap-guide-line {
    background-color: green;
  }

  .multi-wrap-guide:nth-child(3) .multi-wrap-guide-line {
    background-color: yellow;
  }

  .multi-wrap-guide:nth-child(4) .multi-wrap-guide-line {
    background-color: red;
  }
}
```

![colors](https://cloud.githubusercontent.com/assets/1903876/8014943/746e9726-0b9a-11e5-8f9e-64442577382e.png)

Make sure you update to at least version 0.9.0 otherwise this won't work exactly right. Is this about what you had in mind?
