### ISSUE TITLE
How to change line colors for specific languages?

### ISSUE THREAD

**Issue by willfrey** [lexicalunit/multi-wrap-guide#33]
Is there any way to adapt the README example of changing the line colors to apply to a specific language only? In my case, I'm interested in changing Python.

Thank you.

**Comment by lexicalunit** [comment]
@willfrey yep, if you know your source's `data-grammar` you can do it. For example to turn all the lines for Python files blue you'd do:

```less
atom-text-editor[data-grammar="source python"] {
  .vertical .multi-wrap-guide .multi-wrap-guide-line {
    background-color: blue;
  }
}
```
